(function(){'use strict';function q(a,b){this.a=a;this.b=b}var t=0;function u(a){t++;this.name=a;this.a=null;v(this)}function v(a){for(var b=[],d=Math.floor(10*Math.random()+1),c=0;c<d;c++){var e=15*Math.random(),f="SELECT blah FROM something";.2>Math.random()&&(f="<IDLE> in transaction");.1>Math.random()&&(f="vacuum");b.push(new q(e,f))}a.a=b}function w(a){a=a.a.slice();a.sort(function(a,d){return a.a-d.a});for(a=a.slice(0,5);5>a.length;)a.push(new q(0,""));return a};function y(a){this.b=new window.MutationObserver(a);this.a=document.createTextNode("");this.b.observe(this.a,{characterData:!0})}function z(a){var b=this.a="__pms"+Math.random().toString();window.addEventListener("message",function(d){d.source===window&&d.data===b&&a()})}function A(){this.a=0;this.b=[];this.g=this.f=this.c=null}
function C(a){var b,d;d=aa;0===(d.a&8)&&(d.a|=8,window.requestAnimationFrame(d.i));d=d.c;var c;void 0===b&&(b=-1);if(-1===b)d.a|=2,null===d.c&&(d.c=[]),d.c.push(a);else{for(d.a|=1;b>=d.b.length;)d.b.push(null);c=d.b[b];null===c&&(c=d.b[b]=[]);c.push(a)}}
var aa=new function(){this.a=0;this.f=1;this.b=[];this.h=[];this.g=new A;this.c=new A;var a=this;new y(function(){a.a|=256;for(var b=a.b;0<b.length;){a.b=[];for(var d=0;d<b.length;d++)b[d]();b=a.b}a.f++;a.a&=-258});new z(function(){a.a&=-3;a.a|=256;var b=a.h;if(0<b.length){a.h=[];for(var d=0;d<b.length;d++)b[d]()}a.f++;a.a&=-257});this.i=function(){var b,d,c,e,f,h;a.a&=-9;a.a|=256;b=a.c;a.c=a.g;a.g=b;do{for(;0!==(b.a&3);){if(0!==(b.a&1))for(b.a&=-2,d=b.b,f=0;f<d.length;f++)if(c=d[f],null!==c)for(d[f]=
null,h=0;h<c.length;h++)e=c[h],e.constructor===E?F(e):e.call();if(0!==(b.a&2))for(b.a&=-3,c=b.c,f=0;f<c.length;f++)e=c[f],e.constructor===E?F(e):e.call()}for(;0!==(b.a&4);)for(b.a&=-5,c=b.f,b.f=null,f=0;f<c.length;f++)e=c[f],e()}while(0!==(b.a&3));for(;0!==(b.a&8);)for(b.a&=-9,c=b.g,f=0;f<c.length;f++)e=c[f],e();a.f++;a.a&=-257}};function G(a,b,d){this.g=a;this.i=b;this.b=d;this.h=this.a=this.f=this.c=this.j=null}function H(a){return new G(2,a,null)}
function ba(a){var b=J;void 0===a&&(a=null);return new G(4,b,a)}function K(a,b){a.j=b;return a}function L(a,b){a.c=b;return a}function M(a,b){a.f=b;return a}function N(a,b){return a.g===b.g&&a.i===b.i&&a.j===b.j&&!0}function O(a,b){var d=a.g;0!==(d&1)?a.a=document.createTextNode(a.b):0!==(d&2)?a.a=0===(d&16)?document.createElement(a.i):document.createElementNS("http://www.w3.org/2000/svg",a.i):0!==(d&4)&&(d=P(a.i,a.b,b),a.a=d.f,a.h=d)}
function Q(a,b){var d,c;c=a.g;var e,f;if(0!==(c&14))if(d=a.a,e=null,null!==a.j&&(e=a.j),null!==a.c&&(f=a.c.join(" "),e=null===e?f:e+" "+f),null!==e&&(0!==(c&2)?(a.b=e,d.className=e):0!==(c&4)?d.className=e:(f=d.className,d.className=""===f?e:f+" "+e)),0!==(c&4))F(a.h);else if(null!==a.f)if(c=a.f,"string"===typeof c)d.textContent=c;else for(d=0,c=a.f.length;d<c;d++)R(a,a.f[d],null,b)}
function S(a,b,d){var c=a.g,e=a.f;a.a=b;if(0!==(c&4))e=a.i,b=new E(11,e,d,a.b,0,b),null!==e.a&&e.a(b),F(a.h=b);else if(null!==e&&"string"!==typeof e&&0<e.length){for(var c=b.firstChild,f;8===c.nodeType;)f=c,c=c.nextSibling,b.removeChild(f);for(a=0;a<e.length;a++)for(S(e[a],c,d),c=c.nextSibling;8===c.nodeType;)f=c,c=c.nextSibling,b.removeChild(f)}}
function T(a,b,d){var c=a.a,e=a.g,f,h;b.a=c;if(0!==(e&1))a.b!==b.b&&(a.a.nodeValue=b.b);else if(0!==(e&14)){if(0!==(e&2))a.c!==b.c?(null===b.b&&(h=b.j,null!==b.c&&(f=b.c.join(" "),h=null===h?f:h+" "+f),b.b=h),a.b!==b.b&&(c.className=null===b.b?"":b.b)):b.b=a.b;else if(a.c!==b.c){f=a.c;h=b.c;var c=c.classList,g,m,l,k;if(null!==f&&0!==f.length)if(null===h||0===h.length)for(g=0;g<f.length;g++)c.remove(f[g]);else if(1===f.length&&1===h.length)m=f[0],l=h[0],m!==l&&(c.remove(m),c.add(l));else if(1===f.length){m=
f[0];k=-1;for(g=0;g<h.length;g++)if(l=h[g],m===l){k=g;break}else c.add(l);if(-1!==k)for(g=k+1;g<h.length;g++)c.add(h[g]);else c.remove(m)}else if(1===h.length){l=h[0];k=-1;for(g=0;g<f.length;g++)if(m=f[g],m===l){k=g;break}else c.remove(m);if(-1!==k)for(g=k+1;g<f.length;g++)c.remove(f[g]);else c.add(l)}else{k=g=0;for(var n=f.length-1,p=h.length-1,x=!1,r;g<=n&&k<=p&&f[g]===h[k];)g++,k++;for(;g<=n&&k<=p&&f[n]===h[p];)n--,p--;for(var B=Array(p-k+1);g<=n;g++){m=f[g];x=!0;for(r=k;r<=p;r++)if(l=h[r],m===
l){x=!1;B[r-k]=!0;break}x&&c.remove(m)}for(g=k;g<=p;g++)B[g-k]||c.add(h[g])}else if(null!==h&&0<h.length)for(g=0;g<h.length;g++)c.add(h[g])}if(0!==(e&4))d=b.h=a.h,a.b!==b.b&&(d.c=b.b,d.a|=U),F(d);else if(e=a.f,b=b.f,c=0,g=!1,"string"===typeof e)if("string"===typeof b)e!==b&&((d=a.a.firstChild)?d.nodeValue=b:a.a.textContent=b);else{if(null!==b)for(;c<b.length;)R(a,b[c++],null,d)}else if("string"===typeof b){if(null!==e)for(;c<e.length;)V(a,e[c++]);a.a.textContent=b}else if(null!==e&&0!==e.length)if(null===
b||0===b.length)for(;c<e.length;)V(a,e[c++]);else if(1===e.length&&1===b.length)f=e[0],h=b[0],N(f,h)?T(f,h,d):(b=h,e=f,O(b,d),a.a.replaceChild(b.a,e.a),Q(b,d));else if(1===e.length){f=e[0];if(0===(a.g&32))for(;c<b.length;){h=b[c++];if(N(f,h)){T(f,h,d);g=!0;break}R(a,h,f.a,d)}else for(;c<b.length;){h=b[c++];T(f,h,d);g=!0;break}if(g)for(;c<b.length;)R(a,b[c++],null,d);else V(a,f)}else if(1===b.length){h=b[0];if(0===(a.g&32))for(;c<e.length;){f=e[c++];if(N(f,h)){T(f,h,d);g=!0;break}V(a,f)}else for(;c<
e.length;){f=e[c++];T(f,h,d);g=!0;break}if(g)for(;c<e.length;)V(a,e[c++]);else R(a,h,null,d)}else if(0===(a.g&32)){f=c=0;g=e.length-1;for(h=b.length-1;c<=g&&f<=h;){k=e[c];l=b[f];if(!N(k,l))break;c++;f++;T(k,l,d)}for(;c<=g&&f<=h;){k=e[g];l=b[h];if(!N(k,l))break;g--;h--;T(k,l,d)}for(;c<=g&&f<=h;)k=e[c++],l=b[f++],N(k,l)?T(k,l,d):(m=a,n=d,O(l,n),m.a.replaceChild(l.a,k.a),Q(l,n));if(c<=g){do V(a,e[c++]);while(c<g)}else if(f<=h){e=h+1;e=e<b.length?b[e].a:null;do R(a,b[f++],e,d);while(f<h)}}else{f=l=0;
k=e.length-1;m=b.length-1;h=e[l];var c=b[f],I,n=0;a:do for(;;){T(h,c,d);l++;f++;if(l>k||f>m)break a;h=e[l];c=b[f]}while(l<=k&&f<=m);if(l>k)for(k=m+1,k=k<b.length?b[k].a:null;f<=m;)R(a,b[f++],k,d);else if(f>m)for(;l<=k;)V(a,e[l++]);else{p=k-l+1;c=m-f+1;h=Array(c);for(g=0;g<c;g++)h[g]=-1;x=!1;B=0;if(16>=p*c)for(g=l;g<=k;g++){var D=!0;r=e[g];for(l=f;l<=m;){I=b[l];h[l-f]=g;n>l?x=!0:n=l;T(r,I,d);D=!1;break}D&&(V(a,r),B++)}else{D={};for(g=f;g<=m;g++)D[null]=g;for(g=l;g<=k;g++)r=e[g],l=D[null],void 0!==
l?(I=b[l],h[l-f]=g,n>l?x=!0:n=l,T(r,I,d)):(V(a,r),B++)}if(x){g=h.slice(0);e=[];e.push(0);m=0;for(l=h.length;m<l;m++)if(-1!==h[m])if(k=e[e.length-1],h[k]<h[m])g[m]=k,e.push(m);else{k=0;for(n=e.length-1;k<n;)p=(k+n)/2|0,h[e[p]]<h[m]?k=p+1:n=p;h[m]<h[e[k]]&&(0<k&&(g[m]=e[k-1]),e[k]=m)}k=e.length;for(n=e[k-1];0<k--;)e[k]=n,n=g[n];l=e.length-1;for(g=c-1;0<=g;g--)-1===h[g]?(m=g+f,c=b[m],k=m+1,k=k<b.length?b[k].a:null,R(a,c,k,d)):0>l||g!==e[l]?(m=g+f,c=b[m],k=m+1,k=k<b.length?b[k].a:null,a.a.insertBefore(c.a,
k)):l--}else if(p-B!==c)for(g=c-1;0<=g;g--)-1===h[g]&&(m=g+f,c=b[m],k=m+1,k=k<b.length?b[k].a:null,R(a,c,k,d))}}else if(null!==b&&0<b.length)for(c=0;c<b.length;c++)R(a,b[c],null,d)}}function W(a){if(0!==(a.g&4)){a=a.h;a.a&=-3;var b=a.g;if(null!==b)for(var d=0;d<b.length;d++){var c=b[d];c.a.a(c)}a.g=null;b=a.h;if(null!==b)for(d=0;d<b.length;d++)c=b[d],c.a.a(c);a.h=null;null!==a.b&&W(a.b)}else if(null!==a.f&&(a=a.f,"string"!==typeof a))for(b=0;b<a.length;b++)W(a[b])}
function R(a,b,d,c){O(b,c);a.a.insertBefore(b.a,d);Q(b,c)}function V(a,b){a.a.removeChild(b.a);W(b)}function X(){this.c="div";this.b=this.a=null}var U=1;function E(a,b,d,c,e,f){this.a=a;this.i=b;this.j=null===d?0:d.j+1;this.c=c;this.f=f;this.h=this.g=this.b=null}function F(a){3===(a.a&3)&&(a.i.b(a),a.a&=~U)}function Y(a,b){null===a.b?(b.h=a,0!==(a.a&8)?(S(b,a.f,a),a.a&=-9):(b.a=a.f,Q(b,a))):T(a.b,b,a);a.b=b}
function P(a,b,d){b=new E(3,a,d,b,0,document.createElement(a.c));null!==a.a&&a.a(b);return b};function ca(a){this.a=a}var J=new X;J.b=function(a){Y(a,M(L(new G(8,null,null),da),[M(K(H("div"),"popover-content"),a.c.a),K(H("div"),"arrow")]))};var da=["popover","left"];function ea(a){this.a=a}var Z=new X;Z.c="table";Z.a=function(a){function b(){for(var d=a.c.a,c=0;c<d.length;c++)v(d[c]);Z.b(a);window.Monitoring.renderRate.ping();setTimeout(b,0)}b()};
Z.b=function(a){for(var b=a.c.a,d=Array(b.length),c=0;c<b.length;c++){for(var e=b[c],f=w(e),h=e.a.length,e=[M(K(H("td"),"dbname"),e.name),M(K(H("td"),"query-count"),[M(L(K(H("span"),"label"),20<=h?fa:10<=h?ga:ha),""+h)])],h=0;5>h;h++){var g=f[h],m=g.a;e.push(M(L(K(H("td"),"Query"),10<=m?ia:1<=m?ja:ka),[new G(1,null,la(m)),ba(new ca(g.b))]))}d[c]=M(H("tr"),e)}Y(a,M(L(new G(8,null,null),ma),[M(H("tbody"),d)]))};
function la(a){if(!a)return"";var b=parseFloat(a).toFixed(2);60<a&&(b=(a%60).toFixed(2).split("."),b=Math.floor(a/60)+":"+b[0]+"."+b[1]);return b}var ia=["elapsed","warn_long"],ja=["elapsed","warn"],ka=["elapsed","short"],ma=["table","table-striped","latest-data"],fa=["label-important"],ga=["label-warning"],ha=["label-success"];document.addEventListener("DOMContentLoaded",function(){for(var a=[],b=0;100>b;b++)a.push(new u("cluster"+b)),a.push(new u("cluster"+b+"slave"));C(function(){var b=document.getElementById("app"),c=P(Z,new ea(a),null);b.appendChild(c.f);F(c)})});}).call();
