(function(){'use strict';function n(a,b){this.a=a;this.b=b}var p=0;function q(a){p++;this.name=a;this.a=null;r(this)}function r(a){for(var b=[],f=Math.floor(10*Math.random()+1),c=0;c<f;c++){var d=15*Math.random(),e="SELECT blah FROM something";.2>Math.random()&&(e="<IDLE> in transaction");.1>Math.random()&&(e="vacuum");b.push(new n(d,e))}a.a=b}function aa(a){a=a.a.slice();a.sort(function(a,f){return a.a-f.a});for(a=a.slice(0,5);5>a.length;)a.push(new n(0,""));return a};function ba(){this.a=0;this.g=1;this.f=null;this.c=new u;this.b=new u;var a=this;new ca(function(){a.a&=~da;a.a|=v;var b=a.f;if(null!==b){a.f=null;for(var f=0;f<b.length;f++)b[f]()}a.g++;a.a&=~v});this.h=function(){var b,f,c,d,e,g;a.a&=~w;a.a|=v;b=a.b;a.b=a.c;a.c=b;do{for(;0!==(b.a&x);){if(0!==(b.a&y))for(b.a&=~y,f=b.b,e=0;e<f.length;e++)if(c=f[e],null!==c)for(f[e]=null,g=0;g<c.length;g++)d=c[g],d.constructor===B?C(d):d.call();if(0!==(b.a&D))for(b.a&=~D,c=b.c,e=0;e<c.length;e++)d=c[e],d.constructor===
B?C(d):d.call()}for(;0!==(b.a&E);)for(b.a&=~E,c=b.f,b.f=null,e=0;e<c.length;e++)d=c[e],d()}while(0!==(b.a&x));for(;0!==(b.a&F);)for(b.a&=~F,c=b.g,e=0;e<c.length;e++)d=c[e],d();a.g++;a.a&=~v}}var v=1,da=2,w=4;function ca(a){this.b=new window.MutationObserver(a);this.a=document.createTextNode("");this.b.observe(this.a,{characterData:!0})}function u(){this.a=0;this.b=[];this.g=this.f=this.c=null}var y=1,D=2,E=4,F=8,x=3;
function ea(a){var b,f;f=G;0===(f.a&w)&&(f.a|=w,window.requestAnimationFrame(f.h));f=f.b;var c;void 0===b&&(b=-1);if(-1===b)f.a|=D,null===f.c&&(f.c=[]),f.c.push(a);else{for(f.a|=y;b>=f.b.length;)f.b.push(null);c=f.b[b];null===c&&(c=f.b[b]=[]);c.push(a)}}var G=null;function H(a,b,f){this.i=a;this.j=b;this.b=f;this.h=this.a=this.f=this.c=this.g=null}function J(a){return new H(2,a,null)}function fa(a){var b=K;void 0===a&&(a=null);return new H(4,b,a)}function L(a,b){a.g=b;return a}
function M(a,b){a.c=b;return a}function N(a,b){a.f=b;return a}function O(a,b){return a.i===b.i&&a.j===b.j&&a.g===b.g}
function P(a,b){var f,c;c=a.i;var d,e;if(0!==(c&14))if(f=a.a,0!==(c&6)?(d=null,null!==a.g&&(d=a.g),null!==a.c&&(e=a.c.join(" "),d=null===d?e:d+" "+e),null!==d&&(a.b=d,f.className=d)):0!==(c&8)&&(d=null,null!==a.g&&(d=a.g),null!==a.c&&(e=a.c.join(" "),d=null===d?e:d+" "+e),null!==d&&(e=f.className,f.className=""===e?d:e+" "+d)),0!==(c&4))C(a.h);else if(null!==a.f)if(c=a.f,"string"===typeof c)f.textContent=c;else for(f=0,c=a.f.length;f<c;f++)Q(a,a.f[f],null,b)}
function R(a,b,f){var c=a.i,d=a.f;a.a=b;if(0!==(c&4))d=a.j,b=new B(11,d,f,a.b,0,b),null!==d.a&&d.a(b),C(a.h=b);else if(null!==d&&"string"!==typeof d&&0<d.length){for(a=b.firstChild;a.constructor===Comment;)c=a,a=a.nextSibling,b.removeChild(c);for(var e=0;e<d.length;e++)for(R(d[e],a,f),a=a.nextSibling;a.constructor===Comment;)c=a,a=a.nextSibling,b.removeChild(c)}}
function S(a,b,f){var c=a.a,d=a.i,e,g;b.a=c;if(0!==(d&1))a.b!==b.b&&(a.a.nodeValue=b.b);else if(0!==(d&14)){if(0!==(d&2))a.c!==b.c?(null===b.b&&(g=b.g,null!==b.c&&(e=b.c.join(" "),g=null===g?e:g+" "+e),b.b=g),a.b!==b.b&&(null===b.b?c.className="":c.className=g)):b.b=a.b;else if(a.c!==b.c){e=a.c;g=b.c;var c=c.classList,h,k,l,m;if(null!==e&&0!==e.length)if(null===g||0===g.length)for(h=0;h<e.length;h++)c.remove(e[h]);else if(1===e.length&&1===g.length)k=e[0],l=g[0],k!==l&&(c.remove(k),c.add(l));else if(1===
e.length){k=e[0];m=-1;for(h=0;h<g.length;h++)if(l=g[h],k===l){m=h;break}else c.add(l);if(-1!==m)for(h=m+1;h<g.length;h++)c.add(g[h]);else c.remove(k)}else if(1===g.length){l=g[0];m=-1;for(h=0;h<e.length;h++)if(k=e[h],k===l){m=h;break}else c.remove(k);if(-1!==m)for(h=m+1;h<e.length;h++)c.remove(e[h]);else c.add(l)}else{m=h=0;for(var z=e.length-1,t=g.length-1,I=!1,A;h<=z&&m<=t&&e[h]===g[m];)h++,m++;for(;h<=z&&m<=t&&e[z]===g[t];)z--,t--;for(var V=Array(t-m+1);h<=z;h++){k=e[h];I=!0;for(A=m;A<=t;A++)if(l=
g[A],k==l){I=!1;V[A-m]=!0;break}I&&c.remove(k)}for(h=m;h<=t;h++)V[h-m]||c.add(g[h])}else if(null!==g&&0<g.length)for(h=0;h<g.length;h++)c.add(g[h])}if(0!==(d&4))f=b.h=a.h,a.b!==b.b&&f.g.f(f,b.b),C(f);else if(d=a.f,b=b.f,c=0,h=!1,"string"===typeof d)d!==b&&((f=a.a.firstChild)?f.nodeValue=b:a.a.textContent=b);else if(null!==d&&0!==d.length)if(null===b||0===b.length)for(;c<d.length;)T(a,d[c++]);else if(1===d.length&&1===b.length)e=d[0],g=b[0],O(e,g)?S(e,g,f):(T(a,e),Q(a,g,null,f));else if(1===d.length){for(e=
d[0];c<b.length;){g=b[c++];if(O(e,g)){S(e,g,f);h=!0;break}Q(a,g,e.a,f)}if(h)for(;c<b.length;)Q(a,b[c++],null,f);else T(a,e)}else if(1===b.length){for(g=b[0];c<d.length;){e=d[c++];if(O(e,g)){S(e,g,f);h=!0;break}T(a,e)}if(h)for(;c<d.length;)T(a,d[c++]);else Q(a,g,null,f)}else{e=c=0;h=d.length-1;for(g=b.length-1;c<=h&&e<=g;){k=d[c];l=b[e];if(!O(k,l))break;c++;e++;S(k,l,f)}for(;c<=h&&e<=g;){k=d[h];l=b[g];if(!O(k,l))break;h--;g--;S(k,l,f)}for(;c<=h&&e<=g;)k=d[c++],l=b[e++],O(k,l)?S(k,l,f):(Q(a,l,k.a,f),
T(a,k));for(;c<=h;)T(a,d[c++]);d=g+1;for(d=d<b.length?b[d].a:null;e<=g;)Q(a,b[e++],d,f)}else if(null!==b&&0<b.length)for(c=0;c<b.length;c++)Q(a,b[c],null,f)}}function U(a){if(0!==(a.i&4)){a=a.h;a.a&=-3;for(var b=null;null!==b;)b.b.a(b),b=b.a;for(b=null;null!==b;)b.b.a(b),b=b.a;null!==a.c&&U(a.c)}else if(null!==a.f&&(a=a.f,"string"!==typeof a))for(b=0;b<a.length;b++)U(a[b])}
function Q(a,b,f,c){var d=b.i;0!==(d&1)?b.a=document.createTextNode(b.b):0!==(d&2)?b.a=0===(d&16)?document.createElement(b.j):document.createElementNS("http://www.w3.org/2000/svg",b.j):0!==(d&4)&&(d=W(b.j,b.b,c),b.a=d.f,b.h=d);a.a.insertBefore(b.a,f);P(b,c)}function T(a,b){a.a.removeChild(b.a);U(b)}function X(){this.c="div";this.a=null;this.f=ga;this.b=null}function B(a,b,f,c,d,e){this.a=a;this.g=b;this.h=null===f?0:f.h+1;this.b=c;this.f=e;this.c=null}
function C(a){3===(a.a&3)&&(a.g.b(a),a.a&=-2)}function Y(a,b){null===a.c?(b.h=a,0!==(a.a&8)?(R(b,a.f,a),a.a&=-9):(b.a=a.f,P(b,a))):S(a.c,b,a);a.c=b}function ga(a,b){a.b!==b&&(a.b=b,a.a|=1)}function W(a,b,f){b=new B(3,a,f,b,0,document.createElement(a.c));null!==a.a&&a.a(b);return b};function ha(a){this.a=a}var K=new X;K.b=function(a){Y(a,N(M(new H(8,null,null),ia),[N(L(J("div"),"popover-content"),a.b.a),L(J("div"),"arrow")]))};var ia=["popover","left"];function ja(a){this.a=a}var Z=new X;Z.c="table";Z.a=function(a){function b(){for(var f=a.b.a,c=0;c<f.length;c++)r(f[c]);Z.b(a);window.Monitoring.renderRate.ping();setTimeout(b,0)}b()};
Z.b=function(a){for(var b=a.b.a,f=Array(b.length),c=0;c<b.length;c++){for(var d=b[c],e=aa(d),g=d.a.length,d=[N(L(J("td"),"dbname"),d.name),N(L(J("td"),"query-count"),[N(M(L(J("span"),"label"),20<=g?ka:10<=g?la:ma),""+g)])],g=0;5>g;g++){var h=e[g],k=h.a;d.push(N(M(L(J("td"),"Query"),10<=k?na:1<=k?oa:pa),[new H(1,null,qa(k)),fa(new ha(h.b))]))}f[c]=N(J("tr"),d)}Y(a,N(M(new H(8,null,null),ra),[N(J("tbody"),f)]))};
function qa(a){if(!a)return"";var b=parseFloat(a).toFixed(2);60<a&&(b=(a%60).toFixed(2).split("."),b=Math.floor(a/60)+":"+b[0]+"."+b[1]);return b}var na=["elapsed","warn_long"],oa=["elapsed","warn"],pa=["elapsed","short"],ra=["table","table-striped","latest-data"],ka=["label-important"],la=["label-warning"],ma=["label-success"];document.addEventListener("DOMContentLoaded",function(){G=new ba;for(var a=[],b=0;100>b;b++)a.push(new q("cluster"+b)),a.push(new q("cluster"+b+"slave"));ea(function(){var b=document.getElementById("app"),c=W(Z,new ja(a),null);b.appendChild(c.f);C(c)})});}).call();
