(function(){'use strict';var p;function ba(a,b){function c(){}c.prototype=b.prototype;a.prototype=new c;a.prototype.constructor=a;for(var d in b)if(Object.defineProperties){var e=Object.getOwnPropertyDescriptor(b,d);e&&Object.defineProperty(a,d,e)}else a[d]=b[d]}
function r(a,b,c){120!==b.charCodeAt(0)?a.setAttribute(b,c):109===b.charCodeAt(1)&&108===b.charCodeAt(2)?a.setAttributeNS("http://www.w3.org/XML/1998/namespace",b,c):108===b.charCodeAt(1)&&105===b.charCodeAt(2)?a.setAttributeNS("http://www.w3.org/1999/xlink",b,c):a.setAttribute(b,c)}function u(a,b,c){this.a=a;this.i=b;this.h=null;this.f=c;this.s=this.b=this.g=this.l=this.m=this.j=null}p=u.prototype;p.key=function(a){this.h=a;return this};p.u=function(a){this.f=a;return this};
p.data=function(a){this.f=a;return this};p.style=function(a){this.m=a;return this};p.className=function(a){this.l=a;return this};p.children=function(a){this.g=a;return this};p.value=function(a){this.a|=64;this.g=a;return this};p.checked=function(a){this.a|=128;this.g=a;return this};function v(a){if(0===(a.a&4)){if(a=a.g,null!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)v(a[b])}else w(a.s)}
function x(a){if(0===(a.a&4)){if(a=a.g,null!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)x(a[b])}else a.s.detach()}function y(a){if(0===(a.a&256))if(0!==(a.a&4)){a=a.s;a.c|=1;null!==a.v&&0===(a.c&65536)&&y(a.v);0!==(a.c&2)&&ca(a);var b=a.B.ka;null!==b&&b(a,a.u,a.state)}else{if(null!==a.g&&(a=a.g,"string"!==typeof a))for(b=0;b<a.length;b++)y(a[b])}else x(a)}
function da(a,b){var c=a.a;0!==(c&1)?a.b=document.createTextNode(a.f):0!==(c&2)?a.b=0===(c&131072)?0===(c&32768)?document.createElement(a.i):document.createElementNS("http://www.w3.org/2000/svg",a.i):a.i.createElement():0===(c&256)&&(b=ea(a.i,b,a.f),a.b=b.element,a.s=b)}
function A(a,b){var c,d,e,g,f=a.a,h;if(0!==(f&10)){h=a.b;if(0===(f&262144)){var l=a.f;if(null!==l)for(g=Object.keys(l),c=0,d=g.length;c<d;c++)e=g[c],h[e]=l[e];if(null!==a.j)for(g=Object.keys(a.j),c=0,d=g.length;c<d;c++)e=g[c],r(h,e,a.j[e]);null!==a.m&&(0===(f&32768)?h.style.cssText=a.m:h.setAttribute("style",a.m));null!==a.l&&(0===(f&32768)?h.className=a.l:h.setAttribute("class",a.l))}else 0===(f&8)?a.i.A(h,void 0,a.f):b.B.i.A(h,void 0,a.f);e=a.g;if(null!==e)if(0===(a.a&2048))if(0===(a.a&192))if("string"===
typeof e)h.textContent=e;else for(c=0,d=e.length;c<d;c++)B(a,e[c],null,b);else 0!==(a.a&64)?a.b.value=a.g:a.b.checked=a.g;else h.innerHTML=e}else 0!==(f&4)&&C(a.s)}function B(a,b,c,d){a=a.b;null===b.b?(da(b,d),0!==(b.a&4)&&w(b.s),A(b,d),a.insertBefore(b.b,c)):(a.insertBefore(b.b,c),v(b),C(b.s,0===(b.a&512)?b.f:null))}function fa(a,b,c,d){a=a.b;null===b.b?(da(b,d),0!==(b.a&4)&&w(b.s),A(b,d),a.replaceChild(b.b,c.b)):(a.replaceChild(b.b,c.b),v(b),C(b.s,0===(b.a&512)?b.f:null));y(c)}
function D(a,b){a.b.removeChild(b.b);y(b)}function E(a,b){a.b.textContent="";for(a=0;a<b.length;a++)y(b[a])}
function F(a,b,c){var d=a.b,e=a.a,g;b.b=a.b;if(0!==(e&1))a.f!==b.f&&(a.b.nodeValue=b.f);else if(0!==(e&10)){if(0===(e&262144)){if(a.f!==b.f){g=a.f;var f=b.f,h=Object.keys(g),l,m;for(m=0;m<h.length;m++){l=h[m];var k=f[l];g[l]!==k&&(d[l]=k)}}if(a.j!==b.j)if(0===(a.a&32))for(g=a.j,f=b.j,h=Object.keys(g),m=0;m<h.length;m++)l=h[m],k=f[l],g[l]!==k&&r(d,l,k);else if(g=a.j,f=b.j,null!==g)if(null===f)for(l=Object.keys(g),h=0;h<l.length;h++)d.removeAttribute(l[h]);else{l=Object.keys(g);for(h=0;h<l.length;h++)m=
l[h],f.hasOwnProperty(m)?(k=f[m],g[m]!==k&&r(d,m,k)):d.removeAttribute(m);l=Object.keys(f);for(h=0;h<l.length;h++)m=l[h],g.hasOwnProperty(m)||r(d,m,f[m])}else if(null!==f)for(l=Object.keys(f),h=0;h<l.length;h++)m=l[h],r(d,m,f[m]);a.m!==b.m&&(g=null===b.m?"":b.m,0===(e&32768)?d.style.cssText=g:d.setAttribute("style",g));a.l!==b.l&&(g=null===b.l?"":b.l,0===(e&32768)?d.className=g:d.setAttribute("class",g))}else a.f!==b.f&&(0===(e&8)?a.i.A(d,a.f,b.f):c.B.i.A(d,a.f,b.f));if(0===(a.a&192)){if(a.g!==b.g)if(0===
(a.a&2048))if(e=a.g,b=b.g,d=0,h=!1,"string"===typeof e)if(null===b)a.b.removeChild(a.b.firstChild);else if("string"===typeof b)(c=a.b.firstChild)?c.nodeValue=b:a.b.textContent=b;else for(a.b.removeChild(a.b.firstChild);d<b.length;)B(a,b[d++],null,c);else if("string"===typeof b){if(null!==e)for(;d<e.length;)y(e[d++]);a.b.textContent=b}else if(null!==e&&0!==e.length)if(null===b||0===b.length)E(a,e);else if(1===e.length&&1===b.length)g=e[0],f=b[0],G(g,f)?F(g,f,c):fa(a,f,g,c);else if(1===e.length){g=
e[0];if(0===(a.a&16))for(;d<b.length;){f=b[d++];if(G(g,f)){F(g,f,c);h=!0;break}B(a,f,g.b,c)}else for(;d<b.length;){f=b[d++];if(g.h===f.h){F(g,f,c);h=!0;break}B(a,f,g.b,c)}if(h)for(;d<b.length;)B(a,b[d++],null,c);else D(a,g)}else if(1===b.length){f=b[0];if(0===(a.a&16))for(;d<e.length;){if(g=e[d++],G(g,f)){F(g,f,c);h=!0;break}}else for(;d<e.length;)if(g=e[d++],g.h===f.h){F(g,f,c);h=!0;break}if(h){c=0;for(d--;c<d;)D(a,e[c++]);for(d++;d<e.length;)D(a,e[d++])}else E(a,e),B(a,f,null,c)}else if(0===(a.a&
16)){d=f=0;h=e.length-1;for(g=b.length-1;f<=h&&d<=g;){l=e[f];m=b[d];if(!G(l,m))break;f++;d++;F(l,m,c)}for(;f<=h&&d<=g;){l=e[h];m=b[g];if(!G(l,m))break;h--;g--;F(l,m,c)}for(;f<=h&&d<=g;)l=e[f++],m=b[d++],G(l,m)?F(l,m,c):fa(a,m,l,c);if(f<=h){do D(a,e[f++]);while(f<=h)}else if(d<=g){e=g+1;e=e<b.length?b[e].b:null;do B(a,b[d++],e,c);while(d<=g)}}else{d=h=0;l=e.length-1;m=b.length-1;f=e[h];g=b[d];var k=e[l],n=b[m],q,I;a:do{for(;f.h===g.h;){F(f,g,c);h++;d++;if(h>l||d>m)break a;f=e[h];g=b[d]}for(;k.h===
n.h;){F(k,n,c);l--;m--;if(h>l||d>m)break a;k=e[l];n=b[m]}if(f.h===n.h){F(f,n,c);f=m+1;f=f<b.length?b[f].b:null;a.b.insertBefore(n.b,f);h++;m--;if(h>l||d>m)break a;f=e[h];n=b[m];continue a}if(k.h===g.h){F(k,g,c);a.b.insertBefore(g.b,f.b);l--;d++;if(h>l||d>m)break a;k=e[l];g=b[d]}}while(0);if(h>l)for(f=m+1,f=f<b.length?b[f].b:null;d<=m;)B(a,b[d++],f,c);else if(d>m)for(;h<=l;)D(a,e[h++]);else{var Z=l-h+1,f=m-d+1;g=Array(f);for(k=0;k<f;k++)g[k]=-1;var aa=!1,t=0,z=0;if(4>=f||16>=Z*f)for(k=h;k<=l;k++){if(q=
e[k],z<f)for(n=d;n<=m;n++)if(I=b[n],q.h===I.h){g[n-d]=k;t>n?aa=!0:t=n;F(q,I,c);z++;e[k]=null;break}}else{for(var qa=new Map,k=d;k<=m;k++)q=b[k],qa.set(q.h,k);for(k=h;k<=l;k++)q=e[k],z<f&&(n=qa.get(q.h),void 0!==n&&(I=b[n],g[n-d]=k,t>n?aa=!0:t=n,F(q,I,c),z++,e[k]=null))}if(Z===e.length&&0===z)for(E(a,e);d<f;)B(a,b[d++],null,c);else{for(k=Z-z;0<k;)q=e[h++],null!==q&&(D(a,q),k--);if(aa){h=g.slice(0);e=[];e.push(0);l=0;for(m=g.length;l<m;l++)if(-1!==g[l])if(k=e[e.length-1],g[k]<g[l])h[l]=k,e.push(l);
else{k=0;for(n=e.length-1;k<n;)q=(k+n)/2|0,g[e[q]]<g[l]?k=q+1:n=q;g[l]<g[e[k]]&&(0<k&&(h[l]=e[k-1]),e[k]=l)}k=e.length;for(n=e[k-1];0<k--;)e[k]=n,n=h[n];n=e.length-1;for(k=f-1;0<=k;k--)-1===g[k]?(t=k+d,q=b[t],f=t+1,f=f<b.length?b[f].b:null,B(a,q,f,c)):0>n||k!==e[n]?(t=k+d,q=b[t],f=t+1,f=f<b.length?b[f].b:null,a.b.insertBefore(q.b,f)):n--}else if(z!==f)for(k=f-1;0<=k;k--)-1===g[k]&&(t=k+d,q=b[t],f=t+1,f=f<b.length?b[f].b:null,B(a,q,f,c))}}}else{if(null!==b&&0<b.length)for(d=0;d<b.length;d++)B(a,b[d],
null,c)}else d.innerHTML=b.g}else 0!==(e&64)?d.value!==b.g&&(d.value=b.g):d.checked!==b.g&&(d.checked=b.g)}else c=b.s=a.s,0!==(e&1024)&&a.f===b.f||C(c,0===(e&512)?b.f:void 0)}function G(a,b){return a.a===b.a&&a.i===b.i&&a.h===b.h}function H(a){return new u(2,a,null)}function J(){this.o=4;this.a=0;this.i="div";this.ka=this.ja=this.ga=this.Y=this.X=this.A=this.la=null}J.prototype.tagName=function(a){this.i=a;return this};J.prototype.canvas=function(){this.o|=65536;this.a|=65536;this.i="canvas";return this};
J.prototype.update=function(a){this.A=a;return this};J.prototype.w=function(a){return new u(4,this,void 0===a?null:a)};function ea(a,b,c){var d;d=0===(a.a&131072)?0===(a.a&32768)?document.createElement(a.i):document.createElementNS("http://www.w3.org/2000/svg",a.i):a.i.createElement();b=new ga(a.o,a,d,b,c);0!==(a.a&1)&&(d.qa=b);null!==a.X&&(b.state=a.X(b,b.u));null!==a.Y&&a.Y(b,b.u,b.state);return b}
function ga(a,b,c,d,e){this.c=a;this.oa=0;this.B=b;this.element=c;this.depth=void 0===d?0:d.depth+1;this.u=void 0===e?null:e;this.state=null;this.v=0===(a&65536)?null:c.getContext("2d");this.ba=this.$=null}function ha(a){0===(a.c&4)&&(a.c|=4,ia(a))}p=ga.prototype;p.T=function(){return 0===(this.c&131072)?new u(8,null,null):this.B.i.T()};p.update=function(a){C(this,a)};p.L=function(a,b){this.c|=void 0===a?8:a;0===(this.c&5)&&(this.c|=4,(void 0===b?0:b)||ia(this),ja(ka(),this))};
function w(a){la(a);null!==a.v&&0===(a.c&65536)&&v(a.v)}p.detach=function(){null!==this.v&&0===(this.c&65536)&&x(this.v);ca(this)};p.subscribe=function(a){return a.pa(this)};function C(a,b){if(void 0!==b&&0===(a.c&1024)){var c=a.u,d=a.B.la;null!==d?d(a,c,b):ha(a);a.u=b}6===(a.c&6)&&(0===(K&8)||0!==(K&32)||0!==(a.c&256)||0<ma()?(a.B.A(a,a.u,a.state),a.oa=L,a.c&=-133):ja(ka(),a))}function la(a){a.c|=2;var b=a.B.ga;null!==b&&b(a,a.u,a.state)}
function ca(a){0!==(a.c&512)&&(na--,0===na&&(K&=-9,M=0));a.c&=-531;for(var b=a.$;null!==b;)b.ha(),b=b.ia;a.$=null;ia(a);b=a.B.ja;null!==b&&b(a,a.u,a.state)}function ia(a){for(var b=a.ba;null!==b;)b.ha(),b=b.ia;a.ba=null}function oa(a){var b=document.getElementById("app"),c=ea(pa,void 0,a);ka().write(function(){b.appendChild(c.element);la(c);C(c)});return c}function N(){this.a=0;this.H=[];this.D=this.W=this.I=this.J=null}
function ja(a,b){if(0===(b.c&128)){b.c|=128;var c=b.depth;for(a.a|=1;c>=a.H.length;)a.H.push(null);var d=a.H[c];null===d?a.H[c]=[b]:d.push(b)}}N.prototype.write=function(a){this.a|=2;null===this.J&&(this.J=[]);this.J.push(a)};N.prototype.read=function(a){this.a|=4;null===this.I&&(this.I=[]);this.I.push(a)};N.prototype.focus=function(a){this.D=a};var K=0,L=0,ra=[],sa=[],ta=new N,ua=new N,O=[],va=document.createTextNode(""),wa="__kivi"+Math.random(),na=0,P=6,xa=60,Q=0,ya=0,M=0;
(new MutationObserver(za)).observe(va,{characterData:!0});window.addEventListener("message",Aa);function Ba(){0===(K&4)&&(K|=4,requestAnimationFrame(Ca))}function Aa(a){if(a.source===window&&a.data===wa){K&=-3;a=sa;sa=[];for(var b=0;b<a.length;b++)a[b]();L++}}
function Ca(a){var b;K&=-21;0!==(K&8)&&(0<M&&(xa+=.0165*(1E3/(a-M)-xa),Q+=55>xa?-1:1,5<Q?(Q=0,P+=.1):-5>Q&&(Q=0,P*=.66),6<P?P=6:2>P&&(P=2)),M=a,ya=a+P,Ba());var c=ua;ua=ta;ta=c;for(a=0;a<O.length;a++)O[a].c|=4;do{for(;0!==(c.a&4);)for(c.a&=-5,b=c.I,c.I=null,a=0;a<b.length;a++)b[a]();for(;0!==(c.a&3);){if(0!==(c.a&1)){c.a&=-2;var d=c.H;for(a=0;a<d.length;a++){var e=d[a];if(null!==e)for(d[a]=null,b=0;b<e.length;b++)C(e[b])}}if(0!==(c.a&2))for(c.a&=-3,b=c.J,c.J=null,a=0;a<b.length;a++)b[a]()}a=0;for(b=
O.length;a<b;)d=O[a++],0===(d.c&16)?(d.c&=-33,a===b?O.pop():O[--a]=O.pop()):C(d)}while(0!==(c.a&7));for(;0!==(c.a&8);)for(c.a&=-9,b=c.W,c.W=null,a=0;a<b.length;a++)b[a]();null!==c.D&&(c.D.constructor===u?c.D.b.focus():c.D.focus(),c.D=null);0<O.length&&Ba();L++}function za(){for(;0<ra.length;){var a=ra;ra=[];for(var b=0;b<a.length;b++)a[b]();L++}K&=-2}function ka(){Ba();return ua}function ma(){if(0!==(K&16))return 0;var a=ya-performance.now();return 0>=a?(K|=16,0):a}
function R(a){this.o=131072;this.a=0;this.aa=a;this.Z=this.A=this.l=this.m=this.j=this.f=null}p=R.prototype;p.u=function(a){this.f=a;return this};p.style=function(a){this.m=a;return this};p.className=function(a){this.l=a;return this};p.update=function(a){this.o|=262144;this.A=a;return this};p.w=function(a){return new u(2|this.o,this,void 0===a?null:a)};p.T=function(a){return new u(8|this.o,this,void 0===a?null:a)};
p.createElement=function(){var a,b,c,d=this.Z;if(null===d){d=0===(this.a&32768)?document.createElement(this.aa):document.createElementNS("http://www.w3.org/2000/svg",this.aa);if(null!==this.f)for(b=Object.keys(this.f),a=0;a<b.length;a++)c=b[a],d[c]=this.f[c];if(null!==this.j)for(b=Object.keys(this.j),a=0;a<b.length;a++)c=b[a],r(d,c,this.j[c]);null!==this.m&&(0===(this.a&32768)?d.style.cssText=this.m:d.setAttribute("style",this.m));null!==this.l&&(0===(this.a&32768)?d.className=this.l:d.setAttribute("class",
this.l));return 0!==(this.a&1)?(this.Z=d,d.cloneNode(!1)):d}return d.cloneNode(!1)};function Da(a,b){this.U=a;this.query=b}var Ea=new Da(0,"");function S(a){this.id=Fa++;this.name=a;this.V=null;this.update()}S.prototype.update=function(){for(var a=[],b=Math.floor(10*Math.random()+1),c=0;c<b;c++)a.push(new Da(15*Math.random(),.1>Math.random()?"vacuum":.2>Math.random()?"<IDLE> in transaction":"SELECT blah FROM something"));this.V=a};
function Ga(a){a=a.V.slice();a.sort(function(a,c){return a.U-c.U});for(a=a.slice(0,5);5>a.length;)a.push(Ea);return a}var Fa=0;function Ha(a){this.K=[];for(var b=0;b<a;b++)this.K.push(new S("cluster"+b)),this.K.push(new S("cluster"+b+" slave"))}Ha.prototype.update=function(){for(var a=this.K,b=0;b<a.length;b++)a[b]=new S(a[b].name)};function Ia(a,b,c,d){this.min=a;this.max=b;this.da=c;this.ca=d}function Ja(){this.G=[];this.na=100;this.C=-1}function Ka(a,b){a.C=(a.C+1)%a.na;a.G[a.C]=b}
function La(a,b){for(var c=a.G,d=0;d<c.length;d++)b(c[(a.C+1+d)%c.length],d)}function Ma(a){var b=a.G;if(0===b.length)return new Ia(0,0,0,0);for(var c=b[(a.C+1)%b.length],d=c,e=0,g=0;g<b.length;g++){var f=b[(a.C+1+g)%b.length];f<c&&(c=f);f>d&&(d=f);e+=f}return new Ia(c,d,e/b.length,b[a.C])}var Na=[],Oa=-1;function Pa(a){Na.push(a);-1===Oa&&requestAnimationFrame(function(){Oa=-1;var a=Na;Na=[];for(var c=0;c<a.length;c++)a[c]()})}
function T(a){var b=this;this.ma=function(){b.ea();b.S=!1};this.name=a;this.element=document.createElement("div");this.element.style.cssText="padding: 2px;background-color: #020;font-family: monospace;font-size: 12px;color: #0f0";this.S=!1;this.L()}T.prototype.L=function(){this.S||(this.S=!0,Pa(this.ma))};T.prototype.ea=function(){throw Error("sync method not implemented");};
function U(a,b,c,d){T.call(this,a);this.c=b;this.R=c;this.G=d;a=document.createElement("div");a.style.cssText="text-align: center";a.textContent=this.name;c=document.createElement("div");0===(b&1)?(this.P=document.createElement("div"),c.appendChild(this.P)):this.P=null;0===(b&2)?(this.N=document.createElement("div"),c.appendChild(this.N)):this.N=null;0===(b&4)?(this.O=document.createElement("div"),c.appendChild(this.O)):this.O=null;0===(b&8)?(this.M=document.createElement("div"),c.appendChild(this.M)):
this.M=null;this.element.appendChild(a);this.element.appendChild(c);0===(b&16)?(this.canvas=document.createElement("canvas"),this.canvas.style.cssText="display: block; padding: 0; margin: 0",this.canvas.width=100,this.canvas.height=30,this.F=this.canvas.getContext("2d"),this.element.appendChild(this.canvas)):this.F=this.canvas=null}ba(U,T);
U.prototype.ea=function(){var a=this,b=Ma(this.G),c=30/(1.2*b.max),d,e,g;0===(this.c&32)?(d=b.min.toFixed(2),e=b.max.toFixed(2),g=b.da.toFixed(2),b=b.ca.toFixed(2)):(d=Math.round(b.min).toString(),e=Math.round(b.max).toString(),g=Math.round(b.da).toString(),b=Math.round(b.ca).toString());null!==this.P&&(this.P.textContent="min: \u00a0"+d+this.R);null!==this.N&&(this.N.textContent="max: \u00a0"+e+this.R);null!==this.O&&(this.O.textContent="mean: "+g+this.R);null!==this.M&&(this.M.textContent="last: "+
b+this.R);null!==this.F&&(this.F.fillStyle="#010",this.F.fillRect(0,0,100,30),this.F.fillStyle="#0f0",La(this.G,function(b,d){a.F.fillRect(d,30,1,-(b*c))}))};var V=null;function Qa(){V||(V=document.createElement("div"),V.style.cssText="position: fixed;opacity: 0.9;right: 0;bottom: 0",document.body.appendChild(V))}
function Ra(){function a(f){0<e&&(g+=d*(1E3/(f-e)-g));e=f;Ka(b,g);c.L();requestAnimationFrame(a)}Qa();var b=new Ja,c=new U("FPS",39,"",b);V.appendChild(c.element);var d=2/121,e=0,g=60;requestAnimationFrame(a)}function Sa(){function a(){Ka(b,Math.round(performance.memory.usedJSHeapSize/1048576));c.L();setTimeout(a,30)}Qa();if(void 0!==performance.memory){var b=new Ja,c=new U("Memory",5,"MB",b);V.appendChild(c.element);a()}}
function Ta(a){this.data=new Ja;this.fa=new U(a,0,"ms",this.data);this.startTime=-1}var W={};function Ua(a){Qa();var b=W[a];void 0===b&&(W[a]=b=new Ta(a),V.appendChild(b.fa.element))}function Va(a){a=W[a];void 0!==a&&(a.startTime=performance.now())}function Wa(a){var b=performance.now();a=W[a];void 0!==a&&-1!==a.startTime&&(Ka(a.data,b-a.startTime),a.fa.L())}function Xa(a){if(!a)return"";if(60<a){var b=(a%60).toFixed(2).split(".");return Math.floor(a/60)+":"+b[0]+"."+b[1]}return a.toFixed(2)}
var Ya=(new R("div")).className("popover left"),Za=(new R("div")).className("popover-content"),$a=(new R("div")).className("arrow"),ab=(new R("td")).className("dbname"),bb=(new R("td")).className("query-count"),X=new J,cb=(new R("table")).className("table table-striped latest-data");X.o|=cb.o;X.a|=cb.o;X.i=cb;
var pa=X.update(function(a,b){b=b.K;for(var c=Array(b.length),d=0;d<b.length;d++){var e=d,g,f=b[d];g=Ga(f);var h=f.V.length,l=Array(7);l[0]=ab.w().children(f.name);l[1]=bb.w().children([H("span").className(20<=h?"label label-important":10<=h?"label label-warning":"label label-success").children(""+h)]);for(f=0;5>f;f++){var h=g[f],m=h.U;l[f+2]=h!==Ea?H("td").className(10<=m?"Query elapsed warn_long":1<=m?"Query elapsed warn":"Query elapsed short").children([new u(1,null,Xa(m)),Ya.w().children([Za.w().children(h.query),
$a.w()])]):H("td").className("").children([new u(1,null,""),Ya.w().children([Za.w().children(""),$a.w()])])}g=H("tr").children(l);c[e]=g}b=a.T().children([H("tbody").children(c)]);null===a.v?(b.s=a,b.b=a.element,A(b,a)):F(a.v,b,a);a.v=b}),Y=.5;
document.addEventListener("DOMContentLoaded",function(){function a(){Va("data update");for(var c=Y,d=b.K,e=0;e<d.length;e++)Math.random()<c&&(d[e]=new S(d[e].name));ha(g);Wa("data update");Va("view update");g.update();Wa("view update");setTimeout(a,0)}Ra();Sa();Ua("data update");Ua("view update");var b=new Ha(50),c=document.createElement("div");c.style.display="flex";var d=document.createElement("input");d.type="range";d.style.marginBottom="10px";d.style.marginTop="5px";var e=document.createElement("label");
e.textContent="mutations : "+(100*Y).toFixed(0)+"%";d.addEventListener("change",function(a){Y=Number.parseFloat(a.target.value)/100;e.textContent="mutations : "+(100*Y).toFixed(0)+"%"});c.appendChild(e);c.appendChild(d);document.body.insertBefore(c,document.body.firstChild);var g=oa(b);setTimeout(a,0)});}).call();
