(function(){'use strict';function p(a,b){this.a=a;this.b=b};function q(){this.a=0;this.g=[];this.b=this.f=this.c=this.h=null};function t(a){var b=this.a="__pms"+Math.random().toString();window.addEventListener("message",function(c){c.source===window&&c.data===b&&a()})};function u(a){this.b=new window.MutationObserver(a);this.a=document.createTextNode("");this.b.observe(this.a,{characterData:!0})};function v(){this.a=[];this.b=[]}function w(a){for(var b=0,c=a.a;b<c.length;)c[b++]();b=0;for(c=a.b;b<c.length;)c[b].call(c[b+1]),b+=2};new function(){this.a=0;this.c=1;this.b=new v;this.g=new v;this.f=new q;this.h=new q;this.j=[];var a=this;new u(function(){a.a|=256;for(var b=a.b;0!==b.a.length||0!==b.b.length;)a.b=new v,w(b),b=a.b;a.c++;a.a&=-258});new t(function(){a.a&=-3;a.a|=256;var b=a.g;if(0!==b.a.length||0!==b.b.length)a.g=new v,w(b);a.c++;a.a&=-257});this.i=function(){var b=a.j,c,d,e,g,f,h;a.a&=-9;a.a|=256;c=a.h;a.h=a.f;a.f=c;for(f=0;f<b.length;f++)b[f].a|=8;do{for(;0!==(c.a&3);){if(0!==(c.a&1))for(c.a&=-2,d=c.g,f=0;f<d.length;f++)if(e=
d[f],null!==e)for(d[f]=null,h=0;h<e.length;h++)g=e[h],g.constructor===x?A(g):g.call();if(0!==(c.a&2))for(c.a&=-3,e=c.h,f=0;f<e.length;f++)g=e[f],g.constructor===x?A(g):g.call()}f=0;for(h=b.length;f<h;)g=b[f++],0===(g.a&16)?(g.a&=-33,f===h?b.pop():b[--f]=b.pop()):A(g);for(;0!==(c.a&4);)for(c.a&=-5,e=c.c,c.c=null,f=0;f<e.length;f++)g=e[f],g.constructor===x?A(g):g.call()}while(0!==(c.a&3));for(;0!==(c.a&8);)for(c.a&=-9,e=c.f,f=0;f<e.length;f++)g=e[f],g.constructor===x?A(g):g.call();null!==c.b&&(c.b.constructor===
B?c.b.b.focus():c.b.focus(),c.b=null);0<b.length&&0===(a.a&8)&&(a.a|=8,window.requestAnimationFrame(a.i));a.c++;a.a&=-257}};function C(a,b){var c;c="string"===typeof a.b?0===(a.a&1)?document.createElement(a.b):document.createElementNS("http://www.w3.org/2000/svg",a.b):a.b.a();return new x(8,a,b,c)}function x(a,b,c,d){this.a=a;this.i=b;this.j=null===c?0:c.j+1;this.f=null;this.c=d;this.h=this.g=this.b=null}function D(a,b){a.f!==b&&(a.f=b,a.a|=8)}function A(a){10===(a.a&10)&&(a.i.c(a),a.a&=-9)}function E(a){a.a|=2;a=a.b;null!==a&&(a.constructor===B?F(a):a.constructor===x&&E(a))}
function H(a){a.a|=1;var b=a.b;null!==b&&(b.constructor===B?I(b):b.constructor===x&&H(b));a.a&=-19;b=a.g;if(null!==b)if(b.constructor===p)b.b.a(b);else for(var c=0;c<b.length;c++){var d=b[c];d.b.a(d)}a.g=null;b=a.h;if(null!==b)if(b.constructor===p)b.b.a(b);else for(c=0;c<b.length;c++)d=b[c],d.b.a(d);a.h=null};function B(a,b,c){this.a=a;this.h=b;this.f=c;this.g=this.b=this.c=this.i=this.j=null}function J(a,b){a.c=b;return a}B.prototype.value=function(a){this.c=a;return this};function M(a,b){return a.a===b.a&&a.h===b.h&&!0}function N(a,b){var c=a.a;0!==(c&1)?a.b=document.createTextNode(a.f):0!==(c&2)?a.b="string"===typeof a.h?0===(c&16)?document.createElement(a.h):document.createElementNS("http://www.w3.org/2000/svg",a.h):a.h.a():0!==(c&4)&&(c=C(a.h,b),a.b=c.c,a.g=c)}
function O(a,b){var c,d,e,g;c=a.a;var f;if(0!==(c&10)){f=a.b;var h=a.f;if(null!==h)for(g=Object.keys(h),c=0,d=g.length;c<d;c++)e=g[c],f[e]=h[e];null!==a.j&&(f.style.cssText=a.j);null!==a.i&&(f.className=a.i);e=a.c;if(null!==e)if(0===(a.a&768))if("string"===typeof e)f.textContent=e;else for(c=0,d=e.length;c<d;c++)P(a,e[c],null,b);else c=a.b,0!==(a.a&256)?c.value=a.c:c.checked=a.c}else 0!==(c&4)&&(c=a.g,D(c,a.f),A(c))}
function Q(a,b,c){var d=a.a,e=a.c;a.b=b;if(0!==(d&4))b=new x(12,a.h,c,b),b=a.g=b,D(b,a.f),A(b);else if(null!==e&&"string"!==typeof e&&0<e.length){for(var d=b.firstChild,g;8===d.nodeType;)g=d,d=d.nextSibling,b.removeChild(g);for(a=0;a<e.length;a++)for(Q(e[a],d,c),d=d.nextSibling;8===d.nodeType;)g=d,d=d.nextSibling,b.removeChild(g)}}
function R(a,b,c){var d=a.b,e=a.a;b.b=d;if(0!==(e&1))a.f!==b.f&&(a.b.nodeValue=b.f);else if(0!==(e&10)){if(a.f!==b.f){var g=a.f,f=b.f,h,m,l,k,n,r;if(null!==g)if(null===f)for(k=Object.keys(g),h=0,m=k.length;h<m;h++)d[k[h]]=void 0;else{k=Object.keys(g);h=0;for(m=k.length;h<m;h++)l=k[h],f.hasOwnProperty(l)?(n=g[l],r=f[l],n!==r&&(d[l]=r)):d[l]=void 0;k=Object.keys(f);h=0;for(m=k.length;h<m;h++)l=k[h],g.hasOwnProperty(l)||(d[l]=f[l])}else if(null!==f)for(k=Object.keys(f),h=0,m=k.length;h<m;h++)l=k[h],
d[l]=f[l]}a.j!==b.j&&(d.style.cssText=null===b.j?"":b.j);a.i!==b.i&&(d.className=null===b.i?"":b.i);if(0===(a.a&768))if(e=a.c,b=b.c,f=0,h=!1,"string"===typeof e)if(null===b)a.b.removeChild(a.b.firstChild);else if("string"===typeof b)e!==b&&((c=a.b.firstChild)?c.nodeValue=b:a.b.textContent=b);else for(a.b.removeChild(a.b.firstChild);f<b.length;)P(a,b[f++],null,c);else if("string"===typeof b){if(null!==e)for(;f<e.length;)S(a,e[f++]);a.b.textContent=b}else if(null!==e&&0!==e.length)if(null===b||0===
b.length)for(;f<e.length;)S(a,e[f++]);else if(1===e.length&&1===b.length)d=e[0],g=b[0],M(d,g)?R(d,g,c):T(a,g,d,c);else if(1===e.length){d=e[0];if(0===(a.a&32))for(;f<b.length;){g=b[f++];if(M(d,g)){R(d,g,c);h=!0;break}P(a,g,d.b,c)}else for(;f<b.length;){g=b[f++];R(d,g,c);h=!0;break}if(h)for(;f<b.length;)P(a,b[f++],null,c);else S(a,d)}else if(1===b.length){g=b[0];if(0===(a.a&32))for(;f<e.length;){d=e[f++];if(M(d,g)){R(d,g,c);h=!0;break}S(a,d)}else for(;f<e.length;){d=e[f++];R(d,g,c);h=!0;break}if(h)for(;f<
e.length;)S(a,e[f++]);else P(a,g,null,c)}else if(0===(a.a&32)){d=f=0;h=e.length-1;for(g=b.length-1;f<=h&&d<=g;){m=e[f];l=b[d];if(!M(m,l))break;f++;d++;R(m,l,c)}for(;f<=h&&d<=g;){m=e[h];l=b[g];if(!M(m,l))break;h--;g--;R(m,l,c)}for(;f<=h&&d<=g;)m=e[f++],l=b[d++],M(m,l)?R(m,l,c):T(a,l,m,c);if(f<=h){do S(a,e[f++]);while(f<=h)}else if(d<=g){e=g+1;e=e<b.length?b[e].b:null;do P(a,b[d++],e,c);while(d<=g)}}else{d=l=0;k=e.length-1;m=b.length-1;var g=e[l],f=b[d],y,G;n=0;a:do for(;;){R(g,f,c);l++;d++;if(l>k||
d>m)break a;g=e[l];f=b[d]}while(l<=k&&d<=m);if(l>k)for(k=m+1,k=k<b.length?b[k].b:null;d<=m;)P(a,b[d++],k,c);else if(d>m)for(;l<=k;)S(a,e[l++]);else{r=k-l+1;f=m-d+1;g=Array(f);for(h=0;h<f;h++)g[h]=-1;var K=!1,L=0;if(16>=r*f)for(h=l;h<=k;h++){var z=!0;y=e[h];for(l=d;l<=m;){G=b[l];g[l-d]=h;n>l?K=!0:n=l;R(y,G,c);z=!1;break}z&&(S(a,y),L++)}else{z={};for(h=d;h<=m;h++)z[null]=h;for(h=l;h<=k;h++)y=e[h],l=z[null],void 0!==l?(G=b[l],g[l-d]=h,n>l?K=!0:n=l,R(y,G,c)):(S(a,y),L++)}if(K){h=g.slice(0);e=[];e.push(0);
m=0;for(l=g.length;m<l;m++)if(-1!==g[m])if(k=e[e.length-1],g[k]<g[m])h[m]=k,e.push(m);else{k=0;for(n=e.length-1;k<n;)r=(k+n)/2|0,g[e[r]]<g[m]?k=r+1:n=r;g[m]<g[e[k]]&&(0<k&&(h[m]=e[k-1]),e[k]=m)}k=e.length;for(n=e[k-1];0<k--;)e[k]=n,n=h[n];l=e.length-1;for(h=f-1;0<=h;h--)-1===g[h]?(m=h+d,f=b[m],k=m+1,k=k<b.length?b[k].b:null,P(a,f,k,c)):0>l||h!==e[l]?(m=h+d,f=b[m],k=m+1,k=k<b.length?b[k].b:null,a.b.insertBefore(f.b,k)):l--}else if(r-L!==f)for(h=f-1;0<=h;h--)-1===g[h]&&(m=h+d,f=b[m],k=m+1,k=k<b.length?
b[k].b:null,P(a,f,k,c))}}else{if(null!==b&&0<b.length)for(f=0;f<b.length;f++)P(a,b[f],null,c)}else 0!==(e&256)?d.value!==b.c&&(d.value=b.c):d.checked!==b.c&&(d.checked=b.c)}else 0!==(e&4)&&(a=b.g=a.g,D(a,b.f),A(a))}function F(a){if(0===(a.a&4)){if(a=a.c,null!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)F(a[b])}else E(a.g)}function I(a){if(0!==(a.a&4))H(a.g);else if(null!==a.c&&(a=a.c,"string"!==typeof a))for(var b=0;b<a.length;b++)I(a[b])}
function P(a,b,c,d){N(b,d);a.b.insertBefore(b.b,c);0!==(b.a&4)&&E(b.g);O(b,d)}function T(a,b,c,d){N(b,d);a.b.replaceChild(b.b,c.b);I(c);0!==(b.a&4)&&E(b.g);O(b,d)}function S(a,b){a.b.removeChild(b.b);I(b)};var U={};
function V(){this.name="update";this.a=[];this.c=document.createElement("div");this.c.style.cssText="padding: 2px; background-color: #020";this.g=document.createElement("div");this.g.style.cssText="text-align: center; font-size: 12px; color: #0f0";this.g.textContent=this.name;this.h=document.createElement("div");this.h.style.cssText="font-size: 12px; color: #0f0";this.b=document.createElement("canvas");this.b.style.cssText="display: block; padding: 0; margin: 0";this.b.width=200;this.b.height=W;this.c.appendChild(this.g);
this.c.appendChild(this.h);this.c.appendChild(this.b);this.f=this.b.getContext("2d")}var W=100;function X(){var a=document.getElementById("perf"),b=new V;U.update=b;a.appendChild(b.c)}
function aa(a){var b=U.update,c=window.performance.now();a();b.a.push(window.performance.now()-c);200<b.a.length&&b.a.shift();var c=Math.min.apply(Math,b.a),d=Math.max.apply(Math,b.a);a=W/d;b.h.innerHTML="<div>min: "+c.toFixed(3)+"ms</div><div>max: "+d.toFixed(3)+"ms</div><div>now: "+b.a[b.a.length-1].toFixed(3)+"ms</div>";b.f.fillStyle="#010";b.f.fillRect(0,0,200,W);b.f.fillStyle="#0f0";for(c=0;c<b.a.length;c++)b.f.fillRect(c,W,1,-(b.a[c]*a))};function ba(a){var b=document.getElementById("app"),c=C(Y,null);b.appendChild(c.c);c.a|=2;D(c,a);A(c);return c};var Z=.03;function ca(a){for(var b=Z,c=0;c<a.length;c++)for(var d=a[c],e=0;e<d.length;e++)Math.random()<b&&(d[e]=Math.floor(101*Math.random())+0)}var Y=new function(){this.a=0;this.b="div";this.c=null};Y.b="table";
Y.c=function(a){for(var b=a.f,c=Array(b.length),d=0;d<b.length;d++){for(var e=b[d],g=new B(2,"tr",null),f=Array(e.length),h=0;h<e.length;h++){var m=e[h],l=f,k=h,n=new B(2,"td",null);n.i=50<m?"high":"low";l[k]=J(n,m.toString())}c[d]=J(g,f)}b=J(new B(8,null,null),[J(new B(2,"tbody",null),c)]);null===a.b?(b.g=a,0!==(a.a&4)?(Q(b,a.c,a),a.a&=-5):(b.b=a.c,O(b,a))):R(a.b,b,a);a.b=b};
document.addEventListener("DOMContentLoaded",function(){function a(){ca(b);aa(function(){Y.c(f)});requestAnimationFrame(a)}X();for(var b=[],c=0;100>c;c++){for(var d=[],e=0;100>e;e++)d.push(Math.floor(101*Math.random())+0);b.push(d)}c=document.createElement("div");c.style.display="flex";d=document.createElement("input");d.type="range";d.style.width="100%";d.style.margin="5px";d.value=100*Z;var g=document.createElement("label");g.textContent="mutations : "+(100*Z).toFixed(0)+"%";d.addEventListener("change",
function(a){Z=a.target.value/100;g.textContent="mutations : "+(100*Z).toFixed(0)+"%"});c.appendChild(g);c.appendChild(d);document.body.insertBefore(c,document.body.firstChild);var f=ba(b);requestAnimationFrame(a)});}).call();
