(function(){'use strict';function p(a,b){this.a=a;this.b=b};function q(){this.a=0;this.g=[];this.b=this.f=this.c=this.h=null};function t(a){var b=this.a="__pms"+Math.random().toString();window.addEventListener("message",function(c){c.source===window&&c.data===b&&a()})};function u(a){this.b=new window.MutationObserver(a);this.a=document.createTextNode("");this.b.observe(this.a,{characterData:!0})};function v(){this.a=[];this.b=[]}function w(a){for(var b=0,c=a.a;b<c.length;)c[b++]();b=0;for(c=a.b;b<c.length;)c[b].call(c[b+1]),b+=2};new function(){this.a=0;this.c=1;this.b=new v;this.g=new v;this.f=new q;this.h=new q;this.j=[];var a=this;new u(function(){a.a|=256;for(var b=a.b;0!==b.a.length||0!==b.b.length;)a.b=new v,w(b),b=a.b;a.c++;a.a&=-258});new t(function(){a.a&=-3;a.a|=256;var b=a.g;if(0!==b.a.length||0!==b.b.length)a.g=new v,w(b);a.c++;a.a&=-257});this.i=function(){var b=a.j,c,d,g,f,e,h;a.a&=-9;a.a|=256;c=a.h;a.h=a.f;a.f=c;for(e=0;e<b.length;e++)b[e].a|=8;do{for(;0!==(c.a&3);){if(0!==(c.a&1))for(c.a&=-2,d=c.g,e=0;e<d.length;e++)if(g=
d[e],null!==g)for(d[e]=null,h=0;h<g.length;h++)f=g[h],f.constructor===x?A(f):f.call();if(0!==(c.a&2))for(c.a&=-3,g=c.h,e=0;e<g.length;e++)f=g[e],f.constructor===x?A(f):f.call()}e=0;for(h=b.length;e<h;)f=b[e++],0===(f.a&16)?(f.a&=-33,e===h?b.pop():b[--e]=b.pop()):A(f);for(;0!==(c.a&4);)for(c.a&=-5,g=c.c,c.c=null,e=0;e<g.length;e++)f=g[e],f.constructor===x?A(f):f.call()}while(0!==(c.a&3));for(;0!==(c.a&8);)for(c.a&=-9,g=c.f,e=0;e<g.length;e++)f=g[e],f.constructor===x?A(f):f.call();null!==c.b&&(c.b.constructor===
B?c.b.b.focus():c.b.focus(),c.b=null);0<b.length&&0===(a.a&8)&&(a.a|=8,window.requestAnimationFrame(a.i));a.c++;a.a&=-257}};function C(a,b){var c;c="string"===typeof a.b?0===(a.a&1)?document.createElement(a.b):document.createElementNS("http://www.w3.org/2000/svg",a.b):a.b.a();return new x(8,a,b,c)}function x(a,b,c,d){this.a=a;this.i=b;this.j=null===c?0:c.j+1;this.f=null;this.c=d;this.h=this.g=this.b=null}function D(a,b){a.f!==b&&(a.f=b,a.a|=8)}function A(a){10===(a.a&10)&&(a.i.c(a),a.a&=-9)}function E(a){a.a|=2;a=a.b;null!==a&&(a.constructor===B?F(a):a.constructor===x&&E(a))}
function H(a){a.a|=1;var b=a.b;null!==b&&(b.constructor===B?I(b):b.constructor===x&&H(b));a.a&=-19;b=a.g;if(null!==b)if(b.constructor===p)b.b.a(b);else for(var c=0;c<b.length;c++){var d=b[c];d.b.a(d)}a.g=null;b=a.h;if(null!==b)if(b.constructor===p)b.b.a(b);else for(c=0;c<b.length;c++)d=b[c],d.b.a(d);a.h=null};function B(a,b,c){this.a=a;this.i=b;this.g=c;this.h=this.b=this.c=this.f=this.j=null}function J(a,b){a.c=b;return a}B.prototype.value=function(a){this.c=a;return this};function M(a,b){return a.a===b.a&&a.i===b.i&&!0}function N(a,b){var c=a.a;0!==(c&1)?a.b=document.createTextNode(a.g):0!==(c&2)?a.b="string"===typeof a.i?0===(c&16)?document.createElement(a.i):document.createElementNS("http://www.w3.org/2000/svg",a.i):a.i.a():0!==(c&4)&&(c=C(a.i,b),a.b=c.c,a.h=c)}
function O(a,b){var c,d,g,f,e=a.a,h;if(0!==(e&10)){h=a.b;var m=a.g;if(null!==m)for(f=Object.keys(m),c=0,d=f.length;c<d;c++)g=f[c],h[g]=m[g];null!==a.j&&(0===(e&16)?h.style.cssText=a.j:h.setAttribute("style",a.j));null!==a.f&&(0===(e&16)?h.className=a.f:h.setAttribute("class",a.f));e=a.c;if(null!==e)if(0===(a.a&768))if("string"===typeof e)h.textContent=e;else for(c=0,d=e.length;c<d;c++)P(a,e[c],null,b);else h=a.b,0!==(a.a&256)?h.value=a.c:h.checked=a.c}else 0!==(e&4)&&(c=a.h,h=a.b,null!==a.f&&(0===
(e&16)?h.className=a.f:h.setAttribute("class",a.f)),D(c,a.g),A(c))}function Q(a,b,c){var d=a.a,g=a.c;a.b=b;if(0!==(d&4))b=new x(12,a.i,c,b),b=a.h=b,D(b,a.g),A(b);else if(null!==g&&"string"!==typeof g&&0<g.length){for(var d=b.firstChild,f;8===d.nodeType;)f=d,d=d.nextSibling,b.removeChild(f);for(a=0;a<g.length;a++)for(Q(g[a],d,c),d=d.nextSibling;8===d.nodeType;)f=d,d=d.nextSibling,b.removeChild(f)}}
function R(a,b,c){var d=a.b,g=a.a,f;b.b=d;if(0!==(g&1))a.g!==b.g&&(a.b.nodeValue=b.g);else if(0!==(g&10)){if(a.g!==b.g){f=a.g;var e=b.g,h,m,l,k,n,r;if(null!==f)if(null===e)for(k=Object.keys(f),h=0,m=k.length;h<m;h++)d[k[h]]=void 0;else{k=Object.keys(f);h=0;for(m=k.length;h<m;h++)l=k[h],e.hasOwnProperty(l)?(n=f[l],r=e[l],n!==r&&(d[l]=r)):d[l]=void 0;k=Object.keys(e);h=0;for(m=k.length;h<m;h++)l=k[h],f.hasOwnProperty(l)||(d[l]=e[l])}else if(null!==e)for(k=Object.keys(e),h=0,m=k.length;h<m;h++)l=k[h],
d[l]=e[l]}a.j!==b.j&&(f=null===b.j?"":b.j,0===(g&16)?d.style.cssText=f:d.setAttribute("style",f));a.f!==b.f&&(f=null===b.f?"":b.f,0===(g&16)?d.className=f:d.setAttribute("class",f));if(0===(a.a&768))if(g=a.c,b=b.c,e=0,h=!1,"string"===typeof g)if(null===b)a.b.removeChild(a.b.firstChild);else if("string"===typeof b)g!==b&&((c=a.b.firstChild)?c.nodeValue=b:a.b.textContent=b);else for(a.b.removeChild(a.b.firstChild);e<b.length;)P(a,b[e++],null,c);else if("string"===typeof b){if(null!==g)for(;e<g.length;)S(a,
g[e++]);a.b.textContent=b}else if(null!==g&&0!==g.length)if(null===b||0===b.length)for(;e<g.length;)S(a,g[e++]);else if(1===g.length&&1===b.length)d=g[0],f=b[0],M(d,f)?R(d,f,c):T(a,f,d,c);else if(1===g.length){d=g[0];if(0===(a.a&32))for(;e<b.length;){f=b[e++];if(M(d,f)){R(d,f,c);h=!0;break}P(a,f,d.b,c)}else for(;e<b.length;){f=b[e++];R(d,f,c);h=!0;break}if(h)for(;e<b.length;)P(a,b[e++],null,c);else S(a,d)}else if(1===b.length){f=b[0];if(0===(a.a&32))for(;e<g.length;){d=g[e++];if(M(d,f)){R(d,f,c);
h=!0;break}S(a,d)}else for(;e<g.length;){d=g[e++];R(d,f,c);h=!0;break}if(h)for(;e<g.length;)S(a,g[e++]);else P(a,f,null,c)}else if(0===(a.a&32)){d=e=0;h=g.length-1;for(f=b.length-1;e<=h&&d<=f;){m=g[e];l=b[d];if(!M(m,l))break;e++;d++;R(m,l,c)}for(;e<=h&&d<=f;){m=g[h];l=b[f];if(!M(m,l))break;h--;f--;R(m,l,c)}for(;e<=h&&d<=f;)m=g[e++],l=b[d++],M(m,l)?R(m,l,c):T(a,l,m,c);if(e<=h){do S(a,g[e++]);while(e<=h)}else if(d<=f){g=f+1;g=g<b.length?b[g].b:null;do P(a,b[d++],g,c);while(d<=f)}}else{d=l=0;k=g.length-
1;m=b.length-1;f=g[l];var e=b[d],y,G;n=0;a:do for(;;){R(f,e,c);l++;d++;if(l>k||d>m)break a;f=g[l];e=b[d]}while(l<=k&&d<=m);if(l>k)for(k=m+1,k=k<b.length?b[k].b:null;d<=m;)P(a,b[d++],k,c);else if(d>m)for(;l<=k;)S(a,g[l++]);else{r=k-l+1;e=m-d+1;f=Array(e);for(h=0;h<e;h++)f[h]=-1;var K=!1,L=0;if(16>=r*e)for(h=l;h<=k;h++){var z=!0;y=g[h];for(l=d;l<=m;){G=b[l];f[l-d]=h;n>l?K=!0:n=l;R(y,G,c);z=!1;break}z&&(S(a,y),L++)}else{z=new Map;for(h=d;h<=m;h++)z.set(null,h);for(h=l;h<=k;h++)y=g[h],l=z.get(null),void 0!==
l?(G=b[l],f[l-d]=h,n>l?K=!0:n=l,R(y,G,c)):(S(a,y),L++)}if(K){h=f.slice(0);g=[];g.push(0);m=0;for(l=f.length;m<l;m++)if(-1!==f[m])if(k=g[g.length-1],f[k]<f[m])h[m]=k,g.push(m);else{k=0;for(n=g.length-1;k<n;)r=(k+n)/2|0,f[g[r]]<f[m]?k=r+1:n=r;f[m]<f[g[k]]&&(0<k&&(h[m]=g[k-1]),g[k]=m)}k=g.length;for(n=g[k-1];0<k--;)g[k]=n,n=h[n];l=g.length-1;for(h=e-1;0<=h;h--)-1===f[h]?(m=h+d,e=b[m],k=m+1,k=k<b.length?b[k].b:null,P(a,e,k,c)):0>l||h!==g[l]?(m=h+d,e=b[m],k=m+1,k=k<b.length?b[k].b:null,a.b.insertBefore(e.b,
k)):l--}else if(r-L!==e)for(h=e-1;0<=h;h--)-1===f[h]&&(m=h+d,e=b[m],k=m+1,k=k<b.length?b[k].b:null,P(a,e,k,c))}}else{if(null!==b&&0<b.length)for(e=0;e<b.length;e++)P(a,b[e],null,c)}else 0!==(g&256)?d.value!==b.c&&(d.value=b.c):d.checked!==b.c&&(d.checked=b.c)}else 0!==(g&4)&&(a.f!==b.f&&(f=null===b.f?"":b.f,0===(g&16)?d.className=f:d.setAttribute("class",f)),a=b.h=a.h,D(a,b.g),A(a))}
function F(a){if(0===(a.a&4)){if(a=a.c,null!==a&&"string"!==typeof a)for(var b=0;b<a.length;b++)F(a[b])}else E(a.h)}function I(a){if(0!==(a.a&4))H(a.h);else if(null!==a.c&&(a=a.c,"string"!==typeof a))for(var b=0;b<a.length;b++)I(a[b])}function P(a,b,c,d){N(b,d);a.b.insertBefore(b.b,c);0!==(b.a&4)&&E(b.h);O(b,d)}function T(a,b,c,d){N(b,d);a.b.replaceChild(b.b,c.b);I(c);0!==(b.a&4)&&E(b.h);O(b,d)}function S(a,b){a.b.removeChild(b.b);I(b)};var U={};
function V(){this.name="update";this.a=[];this.c=document.createElement("div");this.c.style.cssText="padding: 2px; background-color: #020";this.g=document.createElement("div");this.g.style.cssText="text-align: center; font-size: 12px; color: #0f0";this.g.textContent=this.name;this.h=document.createElement("div");this.h.style.cssText="font-size: 12px; color: #0f0";this.b=document.createElement("canvas");this.b.style.cssText="display: block; padding: 0; margin: 0";this.b.width=200;this.b.height=W;this.c.appendChild(this.g);
this.c.appendChild(this.h);this.c.appendChild(this.b);this.f=this.b.getContext("2d")}var W=100;function X(){var a=document.getElementById("perf"),b=new V;U.update=b;a.appendChild(b.c)}
function aa(a){var b=U.update,c=window.performance.now();a();b.a.push(window.performance.now()-c);200<b.a.length&&b.a.shift();var c=Math.min.apply(Math,b.a),d=Math.max.apply(Math,b.a);a=W/d;b.h.innerHTML="<div>min: "+c.toFixed(3)+"ms</div><div>max: "+d.toFixed(3)+"ms</div><div>now: "+b.a[b.a.length-1].toFixed(3)+"ms</div>";b.f.fillStyle="#010";b.f.fillRect(0,0,200,W);b.f.fillStyle="#0f0";for(c=0;c<b.a.length;c++)b.f.fillRect(c,W,1,-(b.a[c]*a))};function ba(a){var b=document.getElementById("app"),c=C(Y,null);b.appendChild(c.c);c.a|=2;D(c,a);A(c);return c};var Z=.03;function ca(a){for(var b=Z,c=0;c<a.length;c++)for(var d=a[c],g=0;g<d.length;g++)Math.random()<b&&(d[g]=Math.floor(101*Math.random())+0)}var Y=new function(){this.a=0;this.b="div";this.c=null};Y.b="table";
Y.c=function(a){for(var b=a.f,c=Array(b.length),d=0;d<b.length;d++){for(var g=b[d],f=new B(2,"tr",null),e=Array(g.length),h=0;h<g.length;h++){var m=g[h],l=e,k=h,n=new B(2,"td",null);n.f=50<m?"high":"low";l[k]=J(n,m.toString())}c[d]=J(f,e)}b=J(new B(8,null,null),[J(new B(2,"tbody",null),c)]);null===a.b?(b.h=a,0!==(a.a&4)?(Q(b,a.c,a),a.a&=-5):(b.b=a.c,O(b,a))):R(a.b,b,a);a.b=b};
document.addEventListener("DOMContentLoaded",function(){function a(){ca(b);aa(function(){Y.c(e)});requestAnimationFrame(a)}X();for(var b=[],c=0;100>c;c++){for(var d=[],g=0;100>g;g++)d.push(Math.floor(101*Math.random())+0);b.push(d)}c=document.createElement("div");c.style.display="flex";d=document.createElement("input");d.type="range";d.style.width="100%";d.style.margin="5px";d.value=100*Z;var f=document.createElement("label");f.textContent="mutations : "+(100*Z).toFixed(0)+"%";d.addEventListener("change",
function(a){Z=a.target.value/100;f.textContent="mutations : "+(100*Z).toFixed(0)+"%"});c.appendChild(f);c.appendChild(d);document.body.insertBefore(c,document.body.firstChild);var e=ba(b);requestAnimationFrame(a)});}).call();
